# Generated by Django 2.0.6 on 2018-06-25 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitapp', '0009_auto_20180110_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseriesdata',
            name='intraday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeseriesdatatype',
            name='intraday_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='timeseriesdata',
            unique_together={('user', 'resource_type', 'date', 'intraday')},
        ),
    ]
